version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hackrx_postgres
    restart: always
    environment:
      POSTGRES_DB: hackrx_db
      POSTGRES_USER: hackrx_user
      POSTGRES_PASSWORD: hackrx_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./init-scripts:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hackrx_user -d hackrx_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hackrx_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hackrx.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  # Optional: Redis for caching (if needed later)
  redis:
    image: redis:7-alpine
    container_name: hackrx_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  redis_data:
    driver: local